# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [6]:
print('the diameter of{} is {} kilometer .'.format(planet,diameter));

the diameter ofEarth is 12742 kilometer .


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [10]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [13]:
s=np.zeros(10)
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
s=np.ones(10)*5
s

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [18]:
a=np.arange(20,35,2)
a

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
array=np.arange(0,9).reshape(3,3)
array
                      

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [23]:
import pandas as pd


In [24]:
d={"names":["nandhu","madhu","sindhu"],"age":[20,21,24]}
df=pd.DataFrame(d)
df

names  age
0  nandhu   20
1   madhu   21
2  sindhu   24

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [30]:
lists=[[1,'aaa',22],
       [2,'bbb',25],
       [3,'ccc',24]]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [31]:
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24